import { randomBytes } from 'node:crypto';

/**
 * Run-scoped unique-id generators. Every spec that creates data (identities,
 * property assets, listings, admin accounts, leads via reveal-contact) uses
 * these instead of fixed literals, so parallel/repeated runs never collide
 * and specs never depend on execution order or on a previous run's leftover
 * state being cleaned up first.
 *
 * Cleanup strategy (documented once here, applies repo-wide across specs):
 * most entities this suite creates have no DELETE endpoint (property assets,
 * listings, leads, publications — by design, see domain-model.md
 * append-only/soft-lifecycle conventions). Rather than fabricate deletion
 * paths that do not exist in the real API, every such spec uses a
 * unique-per-run identifier (this module) so leftover data from a previous
 * run is simply inert, never collides with, and never has to be found and
 * removed by, a later run. The few entities that DO have a real
 * deactivate/revoke command (admin accounts, permission grants) are left
 * deactivated/revoked by their own spec as part of the scenario itself
 * (that IS the assertion), not as separate teardown.
 */

const RUN_ID = randomBytes(4).toString('hex');

export function runId(): string {
  return RUN_ID;
}

function shortId(): string {
  return randomBytes(4).toString('hex');
}

export function uniqueLogin(prefix: string): string {
  return `${prefix}-${RUN_ID}-${shortId()}@e2e.baza.test`;
}

/**
 * Имя ЖК: читаемое и короткое, а не производное от логина.
 *
 * Раньше засев называл комплекс `E2E ЖК ${login}`, то есть подставлял в
 * заголовок целый email. На детальной странице такой заголовок разрывался
 * посреди слова, и снимок для сверки с Figma переставал что-либо показывать
 * про типографику заголовка.
 */
export function uniqueDevelopmentName(): string {
  return `ЖК Батуми Резиденс ${shortId()}`;
}

export function uniquePhone(): string {
  // +995 (Georgia) prefix to match representativePhone/requesterPhone regex
  // (`^\+?[\d\s-]{6,20}$`) and the domain's Georgia-first market context.
  const suffix = Math.floor(100000000 + Math.random() * 899999999);
  return `+995${suffix}`;
}

export function uniqueCity(): string {
  return `E2E-City-${RUN_ID}-${shortId()}`;
}

export function uniqueAddress(): string {
  return `E2E test address ${RUN_ID}-${shortId()}, generated by apps/e2e-runtime`;
}

export const STRONG_TEST_PASSWORD = 'Correct-Horse-Battery-Staple-1!';
