/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Логин (audience определяется origin запроса, ADR-004) */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Регистрация Identity (domain-model.md Module 1 command `register`) — расширение узкой D-07 spec, тот же паттерн, что unit.price.update/ status.update в D-01: не в исходной D-07 vertical slice, но без этой команды ни одна Identity не может появиться в системе. Не создаёт ERP/Admin ProductAccess сама по себе — только базовую marketplace-способную Identity (ADR-004). */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/developments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список ЖК текущей организации (cursor pagination) */
        get: operations["listDevelopments"];
        put?: never;
        /** Создать draft ЖК (застройщик) */
        post: operations["createDevelopment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/developments/{developmentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить ЖК по id (tenant-scoped) */
        get: operations["getDevelopment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/developments/{developmentId}/buildings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Создать корпус внутри ЖК */
        post: operations["createBuilding"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/buildings/{buildingId}/floors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Создать этаж внутри корпуса */
        post: operations["createFloor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/floors/{floorId}/units": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Создать юнит на этаже (включая kind=parking для отдельной паркинг-шахматки) */
        post: operations["createUnit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/developments/{developmentId}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Публикация ЖК (draft → active, синхронная транзакция + асинхронная projection, ADR-005) */
        post: operations["publishDevelopment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/developments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Публичный поиск ЖК (гость, каталог/карта, MongoDB geo/compound индексы ADR-007) */
        get: operations["searchPublicDevelopments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/developments/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Публичная карточка ЖК по slug (SSR, только status=published) */
        get: operations["getPublicDevelopment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/developments/{slug}/reveal-contact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Раскрытие контакта — отдельная rate-limited команда, создаёт Lead (master plan D-05: контакты отсутствуют в list/search HTML/JSON, reveal отдельная команда с audit/abuse signals) */
        post: operations["revealContact"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leads/{leadId}/assign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** РОП/Директор/Собственник назначает лид на Position менеджера (ручное назначение, не auto) */
        post: operations["assignLead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/publications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin находит publication только в разрешённом scope (мастер-план D-06) — deny-by-default: sourceType/city read-grant'ы admin'а определяют, что видно, sourceType/city query-параметры дополнительно СУЖАЮТ уже разрешённый набор, не расширяют его */
        get: operations["adminListPublications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/publications/{publicationId}/unpublish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin снимает публикацию с публичного каталога — синхронная транзакция (ADR-005 патч), обязательный reason (permission-matrix.md разд.4) */
        post: operations["adminUnpublish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/property-assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список PropertyAsset организации */
        get: operations["listPropertyAssets"];
        put?: never;
        /** Создать PropertyAsset организации */
        post: operations["createPropertyAsset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/property-assets/{assetId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить PropertyAsset по ID (tenant-scoped) */
        get: operations["getPropertyAsset"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/property-assets/{assetId}/listings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список Listing для PropertyAsset */
        get: operations["listListings"];
        put?: never;
        /** Создать Listing для PropertyAsset */
        post: operations["createListing"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/property-assets/{assetId}/listings/{listingId}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Активировать Listing (draft -> active) */
        patch: operations["activateListing"];
        trace?: never;
    };
    "/property-assets/{assetId}/listings/{listingId}/actuality": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить состояние актуальности Listing */
        get: operations["getListingActuality"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/property-assets/{assetId}/listings/{listingId}/confirm-actuality": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Подтвердить актуальность Listing (сброс таймера) */
        patch: operations["confirmListingActuality"];
        trace?: never;
    };
    "/property-assets/{assetId}/duplicate-candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список кандидатов-дублей для PropertyAsset */
        get: operations["getDuplicateCandidates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/property-assets/duplicate-candidates/{duplicateCandidateId}/override": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Owner override дубль-блокировки (подтверждение «это не дубль») */
        post: operations["overrideDuplicateCandidate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/property-assets/{assetId}/listings/{listingId}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** MKT-002: публикация Listing (active → publication_pending, синхронная транзакция + асинхронная projection, ADR-005) — тот же паттерн, что publishDevelopment. Listing.status не меняется этой командой (в отличие от Development draft→active); повторный publish уже published/publication_pending listing отклоняется 409 (не создаёт дублирующую publication/version) — используйте unpublish, затем publish заново. */
        post: operations["publishListing"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/property-assets/{assetId}/listings/{listingId}/unpublish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** MKT-002: owner снимает Listing с публичного каталога — синхронная транзакция (тот же PublicationService.unpublish, что D-06 admin unpublish использует, actorType:identity вместо admin_account) */
        post: operations["unpublishListing"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/property-assets/{assetId}/listings/{listingId}/publication-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ERP polling после publish — читает РЕАЛЬНЫЙ статус MarketplacePublication, не canonical Listing.status (тот же паттерн, что D-03 getPublicationStatus для Development) */
        get: operations["getListingPublicationStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/listings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** MKT-002: публичный поиск вторички/аренды (гость, каталог/карта) — тот же паттерн, что searchPublicDevelopments, дополнительно фильтруется по dealType/propertyType/commercialSubtype */
        get: operations["searchPublicListings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/listings/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Публичная карточка Listing по slug (только status=published). Единый 404 для "не существует" и "slug принадлежит Development/Unit, не Listing" (non-disclosure, тот же принцип, что getPublicDevelopment) */
        get: operations["getPublicListing"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        MoneyAmount: {
            /** @description Никогда float (conventions.md разд.1) */
            amountMinorUnits: number;
            /** @enum {string} */
            currency: "USD" | "GEL" | "RUB";
        };
        ErrorResponse: {
            error: {
                /** @description См. error-catalog.md */
                code: string;
                message: string;
                /** Format: uuid */
                requestId: string;
                details?: {
                    [key: string]: unknown;
                };
            };
        };
        CreateDevelopmentRequest: {
            name: string;
            location: {
                country: string;
                city: string;
                address?: string;
                /** @description GeoJSON Point, [longitude, latitude] — жёсткое требование порядка (ADR-007) */
                geo: {
                    /** @enum {string} */
                    type?: "Point";
                    coordinates?: number[];
                };
            };
            classType?: string;
            /** Format: date */
            completionDate?: string;
        };
        Development: {
            id?: string;
            organizationId?: string;
            name?: string;
            /** @enum {string} */
            status?: "draft" | "active" | "archived";
            location?: Record<string, never>;
            /** @description Optimistic concurrency (conventions.md разд.5) */
            version?: number;
            /** Format: date-time */
            createdAt?: string;
        };
        DevelopmentList: {
            items?: components["schemas"]["Development"][];
            nextCursor?: string | null;
        };
        CreateBuildingRequest: {
            name: string;
            floorsCount: number;
            /** Format: date */
            startDate?: string;
            /** Format: date */
            completionDate?: string;
        };
        Building: {
            id?: string;
            developmentId?: string;
            organizationId?: string;
            name?: string;
            floorsCount?: number;
        };
        CreateFloorRequest: {
            floorNumber: number;
            sectionId?: string | null;
            floorType?: string | null;
        };
        Floor: {
            id?: string;
            buildingId?: string;
            organizationId?: string;
            floorNumber?: number;
        };
        CreateUnitRequest: {
            number: string;
            /**
             * @description parking — отдельная шахматка (domain-model.md Module 4)
             * @enum {string}
             */
            kind: "apartment" | "commercial" | "office" | "parking" | "storage" | "other";
            rooms?: number | null;
            area: number;
            price: components["schemas"]["MoneyAmount"];
            floorPlanId?: string | null;
        };
        Unit: {
            id?: string;
            floorId?: string;
            buildingId?: string;
            organizationId?: string;
            number?: string;
            kind?: string;
            area?: number;
            price?: components["schemas"]["MoneyAmount"];
            /** @enum {string} */
            status?: "available" | "reserved" | "sold" | "hidden";
            version?: number;
        };
        PublicationStatus: {
            id?: string;
            /** @enum {string} */
            sourceType?: "unit" | "development" | "listing";
            sourceId?: string;
            /** @enum {string} */
            status?: "publication_pending" | "published" | "unpublished" | "build_failed";
            slug?: string | null;
            unpublishReason?: string | null;
        };
        PublicDevelopmentList: {
            items?: components["schemas"]["PublicDevelopmentCard"][];
            nextCursor?: string | null;
        };
        /** @description Только whitelist-поля из MarketplacePublication.denormalizedFields (ADR-005) — никогда внутренние комиссии/notes/tenant-only контакты */
        PublicDevelopmentCard: {
            slug?: string;
            name?: string;
            location?: Record<string, never>;
            priceFrom?: components["schemas"]["MoneyAmount"];
            seo?: {
                title?: string;
                description?: string;
                canonicalUrl?: string;
                structuredData?: {
                    [key: string]: unknown;
                };
            };
        };
        RevealContactRequest: {
            requesterName?: string;
            requesterPhone?: string;
            utm?: {
                [key: string]: unknown;
            } | null;
        };
        RevealContactResponse: {
            phone?: string;
            whatsapp?: string | null;
            telegram?: string | null;
            /** @description Lead создан в организации застройщика (D-05) */
            leadId?: string;
        };
        Lead: {
            id?: string;
            organizationId?: string;
            contactId?: string;
            ownerPositionId?: string | null;
            stage?: string;
            source?: {
                [key: string]: unknown;
            };
        };
        PublicListingList: {
            items?: components["schemas"]["PublicListingCard"][];
            nextCursor?: string | null;
        };
        /** @description MKT-002: только whitelist-поля из MarketplacePublication.denormalizedFields (ADR-005, apps/worker/src/handlers/listing-publication.mapper.ts) — никогда organizationId/publisherScope/contact/duplicate signals/audit/ commission. media намеренно отсутствует — PropertyAsset/Listing схема не содержит media-поля в этом проходе (PROP-001 не включал). */
        PublicListingCard: {
            slug?: string;
            /** @enum {string} */
            dealType?: "sale" | "rent_long" | "rent_short";
            price?: components["schemas"]["MoneyAmount"];
            /** @enum {string} */
            propertyType?: "apartment" | "house" | "land" | "commercial";
            /** @enum {string|null} */
            commercialSubtype?: "office" | "warehouse" | "retail" | "business" | "free_purpose" | null;
            location?: Record<string, never>;
            characteristics?: {
                area?: number;
                rooms?: number | null;
                floor?: number | null;
                totalFloors?: number | null;
            };
            seo?: {
                title?: string;
                description?: string;
                canonicalUrl?: string;
                structuredData?: {
                    [key: string]: unknown;
                };
            };
        };
        CreatePropertyAssetRequest: {
            /** @enum {string} */
            propertyType: "apartment" | "house" | "land" | "commercial";
            /** @enum {string} */
            commercialSubtype?: "office" | "warehouse" | "retail" | "business" | "free_purpose";
            location: {
                country: string;
                city: string;
                address: string;
                geo: {
                    /** @enum {string} */
                    type: "Point";
                    coordinates: number[];
                };
            };
            characteristics: {
                area: number;
                rooms?: number;
                floor?: number;
                totalFloors?: number;
            };
            representativePhone: string;
        };
        PropertyAsset: {
            _id?: string;
            publisherScope?: Record<string, never>;
            /** @enum {string} */
            propertyType?: "apartment" | "house" | "land" | "commercial";
            /** @enum {string} */
            commercialSubtype?: "office" | "warehouse" | "retail" | "business" | "free_purpose";
            location?: Record<string, never>;
            characteristics?: Record<string, never>;
            representativePhone?: string;
            version?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        CreateListingRequest: {
            /** @enum {string} */
            dealType: "sale" | "rent_long" | "rent_short";
            price: components["schemas"]["MoneyAmount"];
        };
        Listing: {
            _id?: string;
            propertyAssetId?: string;
            publisherScope?: Record<string, never>;
            /** @enum {string} */
            dealType?: "sale" | "rent_long" | "rent_short";
            price?: components["schemas"]["MoneyAmount"];
            /** @enum {string} */
            status?: "draft" | "active" | "expired" | "archived";
            version?: number;
            /** Format: date-time */
            lastConfirmedAt?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        ListingActuality: {
            status?: string;
            category?: string;
            thresholds?: {
                warningDays?: number;
                overdueDays?: number;
            };
            /** Format: date-time */
            lastConfirmedAt?: string;
            /** @enum {string|null} */
            state?: "fresh" | "warning" | "overdue" | null;
        };
        DuplicateCandidate: {
            id?: string;
            /** @enum {string} */
            status?: "detected" | "confirmed_duplicate" | "override_not_duplicate";
            signals?: {
                phoneMatch?: boolean;
                addressMatch?: boolean;
                roomsAreaFloorMatch?: boolean;
            };
            overrideReason?: string;
            /** Format: date-time */
            overrideAt?: string;
            /** Format: date-time */
            detectedAt?: string;
        };
    };
    responses: {
        /** @description Стандартный формат ошибки (conventions.md разд.3) */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        Cursor: string;
        Limit: number;
        DevelopmentId: string;
        AssetId: string;
        ListingId: string;
        /** @description ADR-006 — обязателен для publish/book/cancel/manual-ledger */
        IdempotencyKeyHeader: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    login: string;
                    /** Format: password */
                    password: string;
                };
            };
        };
        responses: {
            /** @description Успешный логин, session cookie установлена */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        identityId?: string;
                        requires2fa?: boolean;
                    };
                };
            };
            401: components["responses"]["Error"];
            429: components["responses"]["Error"];
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    login: string;
                    /** Format: password */
                    password: string;
                };
            };
        };
        responses: {
            /** @description Identity создана (без сессии — отдельный /auth/login вызов после) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        identityId?: string;
                    };
                };
            };
            /** @description normalizedLogin уже занят (domain-model.md invariant — уникален глобально) */
            409: components["responses"]["Error"];
        };
    };
    listDevelopments: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список ЖК */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevelopmentList"];
                };
            };
        };
    };
    createDevelopment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDevelopmentRequest"];
            };
        };
        responses: {
            /** @description Development создан в статусе draft */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Development"];
                };
            };
            400: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    getDevelopment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                developmentId: components["parameters"]["DevelopmentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Development */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Development"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    createBuilding: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                developmentId: components["parameters"]["DevelopmentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBuildingRequest"];
            };
        };
        responses: {
            /** @description Building создан */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Building"];
                };
            };
        };
    };
    createFloor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                buildingId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFloorRequest"];
            };
        };
        responses: {
            /** @description Floor создан */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Floor"];
                };
            };
        };
    };
    createUnit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                floorId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUnitRequest"];
            };
        };
        responses: {
            /** @description Unit создан в статусе available */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Unit"];
                };
            };
        };
    };
    publishDevelopment: {
        parameters: {
            query?: never;
            header: {
                /** @description ADR-006 — обязателен для publish/book/cancel/manual-ledger */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyHeader"];
            };
            path: {
                developmentId: components["parameters"]["DevelopmentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Publication принята, статус publication_pending (ADR-005 патч — worker строит полную проекцию асинхронно, этот ответ не ждёт его завершения) */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicationStatus"];
                };
            };
            /** @description PUBLICATION_SOURCE_NOT_READY */
            400: components["responses"]["Error"];
            /** @description IDEMPOTENCY_KEY_CONFLICT */
            409: components["responses"]["Error"];
        };
    };
    searchPublicDevelopments: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
                /** @description bounding box для поиска по области карты: minLng,minLat,maxLng,maxLat */
                bbox?: string;
                city?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список публичных карточек (whitelist-поля из MarketplacePublication, ADR-005) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicDevelopmentList"];
                };
            };
            /** @description VALIDATION_FAILED — невалидный cursor/limit/bbox или неизвестный query-параметр (D-04A) */
            400: components["responses"]["Error"];
        };
    };
    getPublicDevelopment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Публичная карточка */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicDevelopmentCard"];
                };
            };
            /** @description PUBLICATION_NOT_FOUND */
            404: components["responses"]["Error"];
        };
    };
    revealContact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevealContactRequest"];
            };
        };
        responses: {
            /** @description Контакт раскрыт, Lead создан в организации застройщика */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevealContactResponse"];
                };
            };
            /** @description RATE_LIMITED */
            429: components["responses"]["Error"];
        };
    };
    assignLead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leadId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    assigneePositionId: string;
                };
            };
        };
        responses: {
            /** @description Лид назначен */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lead"];
                };
            };
            /** @description FORBIDDEN — нет lead.assign.organization */
            403: components["responses"]["Error"];
        };
    };
    adminListPublications: {
        parameters: {
            query?: {
                sourceType?: "development" | "unit" | "listing";
                city?: string;
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список publication в разрешённом scope, ЛЮБОЙ статус (не только published — admin должен видеть publication_pending/unpublished/ build_failed тоже) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: {
                            id?: string;
                            sourceType?: string;
                            sourceId?: string;
                            organizationId?: string | null;
                            status?: string;
                            slug?: string | null;
                            publishedAt?: string | null;
                            unpublishedAt?: string | null;
                            unpublishReason?: string | null;
                            city?: string | null;
                        }[];
                        nextCursor?: string | null;
                    };
                };
            };
            /** @description VALIDATION_FAILED */
            400: components["responses"]["Error"];
        };
    };
    adminUnpublish: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publicationId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    reason: string;
                };
            };
        };
        responses: {
            /** @description Публикация скрыта немедленно (синхронно), canonical-статус изменён, audit event записан в той же транзакции */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicationStatus"];
                };
            };
            /** @description ADMIN_REASON_REQUIRED */
            400: components["responses"]["Error"];
            /** @description FORBIDDEN / ADMIN_SCOPE_INSUFFICIENT */
            403: components["responses"]["Error"];
        };
    };
    listPropertyAssets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список PropertyAsset */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyAsset"][];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    createPropertyAsset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePropertyAssetRequest"];
            };
        };
        responses: {
            /** @description PropertyAsset создан */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyAsset"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    getPropertyAsset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assetId: components["parameters"]["AssetId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description PropertyAsset найден */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyAsset"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    listListings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assetId: components["parameters"]["AssetId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список Listing */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Listing"][];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    createListing: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assetId: components["parameters"]["AssetId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateListingRequest"];
            };
        };
        responses: {
            /** @description Listing создан */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Listing"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    activateListing: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assetId: components["parameters"]["AssetId"];
                listingId: components["parameters"]["ListingId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Listing активирован */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Listing"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            /** @description Уже есть активный listing для этого dealType или статус не draft */
            409: components["responses"]["Error"];
        };
    };
    getListingActuality: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assetId: components["parameters"]["AssetId"];
                listingId: components["parameters"]["ListingId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Состояние актуальности */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingActuality"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    confirmListingActuality: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assetId: components["parameters"]["AssetId"];
                listingId: components["parameters"]["ListingId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    expectedVersion: number;
                };
            };
        };
        responses: {
            /** @description Актуальность подтверждена, возвращает обновлённое состояние актуальности */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingActuality"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            /** @description Version conflict / Listing is not active or expired */
            409: components["responses"]["Error"];
        };
    };
    getDuplicateCandidates: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assetId: components["parameters"]["AssetId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список кандидатов-дублей */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DuplicateCandidate"][];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    overrideDuplicateCandidate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                duplicateCandidateId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    reason: string;
                };
            };
        };
        responses: {
            /** @description Дубль снят (status override_not_duplicate) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id?: string;
                        /** @enum {string} */
                        status?: "override_not_duplicate";
                    };
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            /** @description Duplicate candidate status is not 'detected' */
            409: components["responses"]["Error"];
        };
    };
    publishListing: {
        parameters: {
            query?: never;
            header: {
                /** @description ADR-006 — обязателен для publish/book/cancel/manual-ledger */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyHeader"];
            };
            path: {
                assetId: components["parameters"]["AssetId"];
                listingId: components["parameters"]["ListingId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Publication принята, статус publication_pending */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicationStatus"];
                };
            };
            /** @description Listing не найден / чужая организация (единый non-disclosure код) */
            404: components["responses"]["Error"];
            /** @description Listing status не 'active' (draft/expired/archived) ИЛИ публикация уже существует в статусе, отличном от unpublished/build_failed */
            409: components["responses"]["Error"];
        };
    };
    unpublishListing: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assetId: components["parameters"]["AssetId"];
                listingId: components["parameters"]["ListingId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    reason: string;
                };
            };
        };
        responses: {
            /** @description Публикация скрыта немедленно (синхронно) — 201, не 200 (Nest default для POST без явного @HttpCode, задокументировано как фактическое поведение, не переопределено этим проходом) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicationStatus"];
                };
            };
            404: components["responses"]["Error"];
            /** @description Publication уже не в статусе published */
            409: components["responses"]["Error"];
        };
    };
    getListingPublicationStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assetId: components["parameters"]["AssetId"];
                listingId: components["parameters"]["ListingId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Publication status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicationStatus"];
                };
            };
            /** @description Listing не существует/чужой ИЛИ публикация никогда не запускалась (единый non-disclosure код) */
            404: components["responses"]["Error"];
        };
    };
    searchPublicListings: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
                /** @description bounding box для поиска по области карты: minLng,minLat,maxLng,maxLat */
                bbox?: string;
                city?: string;
                dealType?: "sale" | "rent_long" | "rent_short";
                propertyType?: "apartment" | "house" | "land" | "commercial";
                commercialSubtype?: "office" | "warehouse" | "retail" | "business" | "free_purpose";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список публичных карточек (whitelist-поля из MarketplacePublication, ADR-005) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicListingList"];
                };
            };
            /** @description VALIDATION_FAILED — невалидный cursor/limit/bbox/enum-значение или неизвестный query-параметр */
            400: components["responses"]["Error"];
        };
    };
    getPublicListing: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Публичная карточка */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicListingCard"];
                };
            };
            /** @description PUBLICATION_NOT_FOUND */
            404: components["responses"]["Error"];
        };
    };
}
